"""create ix_name_author_id_type_active on tags

Revision ID: 00f7105350d4
Revises: b24ff827f595
Create Date: 2024-04-23 17:31:36.900168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f7105350d4'
down_revision = 'b24ff827f595'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_name_author_id_type_active', 'tags', ['name', 'author_id', 'type'], unique=True, schema='recipes_catalog', postgresql_where=sa.text('discarded = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_name_author_id_type_active', table_name='tags', schema='recipes_catalog', postgresql_where=sa.text('discarded = false'))
    # ### end Alembic commands ###
