"""create menus tags association table

Revision ID: 082ec09c42ff
Revises: 8bbd0d2e6d93
Create Date: 2025-01-23 10:07:42.821045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '082ec09c42ff'
down_revision = '8bbd0d2e6d93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus_tags_association',
    sa.Column('menu_id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['recipes_catalog.menus.id'], name=op.f('fk_menus_tags_association_menu_id_menus')),
    sa.ForeignKeyConstraint(['tag_id'], ['shared_kernel.tags.id'], name=op.f('fk_menus_tags_association_tag_id_tags')),
    sa.PrimaryKeyConstraint('menu_id', 'tag_id', name=op.f('pk_menus_tags_association')),
    schema='recipes_catalog'
    )
    op.drop_index('ix_products_catalog_tags_created_at', table_name='classifications', schema='products_catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_products_catalog_tags_created_at', 'classifications', ['created_at'], unique=False, schema='products_catalog')
    op.drop_table('menus_tags_association', schema='recipes_catalog')
    # ### end Alembic commands ###
