"""move diet type to shared kernel

Revision ID: 21c419b0b4a7
Revises: b6667ac48aca
Create Date: 2024-06-16 18:41:16.634303

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "21c419b0b4a7"
down_revision = "b6667ac48aca"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "diet_types",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("author_id", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("privacy", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("discarded", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_diet_types")),
        schema="shared_kernel",
    )
    op.create_table(
        "products_allergens_association",
        sa.Column("product_id", sa.String(), nullable=False),
        sa.Column("allergen_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["allergen_id"],
            ["shared_kernel.allergens.id"],
            name=op.f("fk_products_allergens_association_allergen_id_allergens"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products_catalog.products.id"],
            name=op.f("fk_products_allergens_association_product_id_products"),
        ),
        sa.PrimaryKeyConstraint(
            "product_id", "allergen_id", name=op.f("pk_products_allergens_association")
        ),
        schema="products_catalog",
    )
    op.create_table(
        "products_diet_types_association",
        sa.Column("product_id", sa.String(), nullable=False),
        sa.Column("diet_type_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["diet_type_id"],
            ["shared_kernel.diet_types.id"],
            name=op.f("fk_products_diet_types_association_diet_type_id_diet_types"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products_catalog.products.id"],
            name=op.f("fk_products_diet_types_association_product_id_products"),
        ),
        sa.PrimaryKeyConstraint(
            "product_id",
            "diet_type_id",
            name=op.f("pk_products_diet_types_association"),
        ),
        schema="products_catalog",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("products_diet_types_association", schema="products_catalog")
    op.drop_table("products_allergens_association", schema="products_catalog")
    op.drop_table("diet_types", schema="shared_kernel")
    # ### end Alembic commands ###
