"""added multiple indexes

Revision ID: 2a2dd2771cd1
Revises: fa62c389a034
Create Date: 2024-11-06 19:30:52.977835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a2dd2771cd1'
down_revision = 'fa62c389a034'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_recipes_catalog_ingredients_product_id'), 'ingredients', ['product_id'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_recipes_calorie_density'), 'recipes', ['calorie_density'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_recipes_calories'), 'recipes', ['calories'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_recipes_carbo_percentage'), 'recipes', ['carbo_percentage'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_recipes_carbohydrate'), 'recipes', ['carbohydrate'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_recipes_cuisine_id'), 'recipes', ['cuisine_id'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_recipes_flavor_id'), 'recipes', ['flavor_id'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_recipes_protein'), 'recipes', ['protein'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_recipes_protein_percentage'), 'recipes', ['protein_percentage'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_recipes_texture_id'), 'recipes', ['texture_id'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_recipes_total_fat'), 'recipes', ['total_fat'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_recipes_total_fat_percentage'), 'recipes', ['total_fat_percentage'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_recipes_total_time'), 'recipes', ['total_time'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_shared_kernel_diet_types_name'), 'diet_types', ['name'], unique=False, schema='shared_kernel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_kernel_diet_types_name'), table_name='diet_types', schema='shared_kernel')
    op.drop_index(op.f('ix_recipes_catalog_recipes_total_time'), table_name='recipes', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_recipes_total_fat_percentage'), table_name='recipes', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_recipes_total_fat'), table_name='recipes', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_recipes_texture_id'), table_name='recipes', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_recipes_protein_percentage'), table_name='recipes', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_recipes_protein'), table_name='recipes', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_recipes_flavor_id'), table_name='recipes', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_recipes_cuisine_id'), table_name='recipes', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_recipes_carbohydrate'), table_name='recipes', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_recipes_carbo_percentage'), table_name='recipes', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_recipes_calories'), table_name='recipes', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_recipes_calorie_density'), table_name='recipes', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_ingredients_product_id'), table_name='ingredients', schema='recipes_catalog')
    # ### end Alembic commands ###
