"""add calorie density and other columns to recipes table

Revision ID: 2d51a015f6a9
Revises: d8bbd0841f64
Create Date: 2024-04-27 17:57:20.479433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d51a015f6a9'
down_revision = 'd8bbd0841f64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('calorie_density', sa.Boolean(), nullable=True), schema='recipes_catalog')
    op.add_column('recipes', sa.Column('carbo_percentage', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('recipes', sa.Column('protein_percentage', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('recipes', sa.Column('total_fat_percentage', sa.Float(), nullable=True), schema='recipes_catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'total_fat_percentage', schema='recipes_catalog')
    op.drop_column('recipes', 'protein_percentage', schema='recipes_catalog')
    op.drop_column('recipes', 'carbo_percentage', schema='recipes_catalog')
    op.drop_column('recipes', 'calorie_density', schema='recipes_catalog')
    # ### end Alembic commands ###
