"""add allergens to recipes table

Revision ID: 3ac3e499d9a7
Revises: 8a3ef0281f34
Create Date: 2024-10-16 20:44:56.596200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ac3e499d9a7'
down_revision = '8a3ef0281f34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes_allergens_association',
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('allergen_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['allergen_name'], ['shared_kernel.allergens.id'], name=op.f('fk_recipes_allergens_association_allergen_name_allergens')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes_catalog.recipes.id'], name=op.f('fk_recipes_allergens_association_recipe_id_recipes')),
    sa.PrimaryKeyConstraint('recipe_id', 'allergen_name', name=op.f('pk_recipes_allergens_association')),
    schema='recipes_catalog'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes_allergens_association', schema='recipes_catalog')
    # ### end Alembic commands ###
