"""fix user_id type on onboarding_forms

Revision ID: 400c5c7a9839
Revises: c0a08369503c
Create Date: 2025-08-12 17:20:39.499870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400c5c7a9839'
down_revision = 'c0a08369503c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('onboarding_forms', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False,
               schema='client_onboarding')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('onboarding_forms', 'user_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               schema='client_onboarding')
    # ### end Alembic commands ###
