"""add menu_id to meals

Revision ID: 42116dd72ac9
Revises: 061db573f365
Create Date: 2025-02-20 17:18:40.445467

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "42116dd72ac9"
down_revision = "061db573f365"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Rename table
    op.rename_table("menu_items", "menu_meals", schema="recipes_catalog")

    # Rename indexes
    op.execute(
        "ALTER INDEX recipes_catalog.ix_recipes_catalog_menu_items_meal_type RENAME TO ix_recipes_catalog_menu_meals_meal_type"
    )
    op.execute(
        "ALTER INDEX recipes_catalog.menu_items_menu_id_meal_type_idx RENAME TO menu_meals_menu_id_meal_type_idx"
    )
    op.execute(
        "ALTER INDEX recipes_catalog.menu_items_menu_id_week_weekday_meal_type_idx RENAME TO menu_meals_menu_id_week_weekday_meal_type_idx"
    )

    op.execute(
        'DROP INDEX IF EXISTS shared_kernel."tags_key_value_author_id_type,unique"'
    )

    # Create new correctly named indexes
    op.create_index(
        "ix_tags_key_value_author_id_type",
        "tags",
        ["key", "value", "author_id", "type"],
        unique=True,
        schema="shared_kernel",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "source_id",
        existing_type=sa.VARCHAR(),
        nullable=False,
        schema="products_catalog",
    )
    op.add_column(
        "meals",
        sa.Column("menu_id", sa.String(), nullable=True),
        schema="recipes_catalog",
    )
    op.create_index(
        op.f("ix_recipes_catalog_meals_menu_id"),
        "meals",
        ["menu_id"],
        unique=False,
        schema="recipes_catalog",
    )
    op.create_foreign_key(
        op.f("fk_meals_menu_id_menus"),
        "meals",
        "menus",
        ["menu_id"],
        ["id"],
        source_schema="recipes_catalog",
        referent_schema="recipes_catalog",
    )
    op.drop_index("tags_author_id_type", table_name="tags", schema="shared_kernel")
    op.create_index(
        "tags_author_id_type,unique",
        "tags",
        ["author_id", "type"],
        unique=False,
        schema="shared_kernel",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "tags_author_id_type,unique", table_name="tags", schema="shared_kernel"
    )
    op.create_index(
        "tags_author_id_type",
        "tags",
        ["author_id", "type"],
        unique=False,
        schema="shared_kernel",
    )
    op.drop_constraint(
        op.f("fk_meals_menu_id_menus"),
        "meals",
        schema="recipes_catalog",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_recipes_catalog_meals_menu_id"),
        table_name="meals",
        schema="recipes_catalog",
    )
    op.drop_column("meals", "menu_id", schema="recipes_catalog")
    op.alter_column(
        "products",
        "source_id",
        existing_type=sa.VARCHAR(),
        nullable=True,
        schema="products_catalog",
    )
    # ### end Alembic commands ###
    # Revert table rename
    op.rename_table("menu_meals", "menu_items", schema="recipes_catalog")

    # Revert index names
    op.execute(
        "ALTER INDEX recipes_catalog.ix_recipes_catalog_menu_meals_meal_type RENAME TO ix_recipes_catalog_menu_items_meal_type"
    )
    op.execute(
        "ALTER INDEX recipes_catalog.menu_meals_menu_id_meal_type_idx RENAME TO menu_items_menu_id_meal_type_idx"
    )
    op.execute(
        "ALTER INDEX recipes_catalog.menu_meals_menu_id_week_weekday_meal_type_idx RENAME TO menu_items_menu_id_week_weekday_meal_type_idx"
    )

    op.drop_index(
        "ix_tags_key_value_author_id_type", table_name="tags", schema="shared_kernel"
    )

    # Recreate the original incorrect indexes
    op.create_index(
        "tags_key_value_author_id_type,unique",
        "tags",
        ["key", "value", "author_id", "type"],
        unique=True,
        schema="shared_kernel",
    )
