"""drop uq_recipes_catalog_ingredients_recipe_id_position

Revision ID: a243355adf21
Revises: bc5c8a8b3b56
Create Date: 2025-05-12 15:25:39.016043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a243355adf21'
down_revision = 'bc5c8a8b3b56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_recipes_catalog_ingredients_recipe_id_position', 'ingredients', schema='recipes_catalog', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_recipes_catalog_ingredients_recipe_id_position', 'ingredients', ['recipe_id', 'position'], schema='recipes_catalog')
    # ### end Alembic commands ###
