"""populate brands and sources and delete them from tags

Revision ID: a5daf24b2dff
Revises: be994c352989
Create Date: 2024-03-26 14:04:08.252955

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a5daf24b2dff"
down_revision = "be994c352989"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_products_catalog_products_source_id"),
        "products",
        ["source_id"],
        unique=False,
        schema="products_catalog",
    )
    op.drop_constraint(
        "fk_products_source_id_tags",
        "products",
        schema="products_catalog",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_products_brand_id_tags",
        "products",
        schema="products_catalog",
        type_="foreignkey",
    )
    # op.execute(
    #     f"""
    #     INSERT INTO products_catalog.brands (id, name, author_id, author_role, description, created_at, updated_at, discarded, version)
    #     SELECT
    #         id,
    #         name,
    #         author_id,
    #         author_role,
    #         description,
    #         created_at,
    #         updated_at,
    #         discarded,
    #         version
    #     FROM products_catalog.tags
    #     WHERE type = 'brand'
    #     """
    # )
    # op.execute(
    #     f"""
    #     INSERT INTO products_catalog.sources (id, name, author_id, author_role, description, created_at, updated_at, discarded, version)
    #     SELECT
    #         id,
    #         name,
    #         author_id,
    #         author_role,
    #         description,
    #         created_at,
    #         updated_at,
    #         discarded,
    #         version
    #     FROM products_catalog.tags
    #     WHERE type = 'source'
    #     """
    # )
    # op.execute(
    #     """
    #     DELETE FROM products_catalog.tags
    #     WHERE type = 'source'
    #     """
    # )
    # op.execute(
    #     """
    #     DELETE FROM products_catalog.tags
    #     WHERE type = 'brand'
    #     """
    # )
    op.create_foreign_key(
        op.f("fk_products_source_id_sources"),
        "products",
        "sources",
        ["source_id"],
        ["id"],
        source_schema="products_catalog",
        referent_schema="products_catalog",
    )
    op.create_foreign_key(
        op.f("fk_products_brand_id_brands"),
        "products",
        "brands",
        ["brand_id"],
        ["id"],
        source_schema="products_catalog",
        referent_schema="products_catalog",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_products_brand_id_brands"),
        "products",
        schema="products_catalog",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_products_source_id_sources"),
        "products",
        schema="products_catalog",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_products_brand_id_tags",
        "products",
        "tags",
        ["brand_id"],
        ["id"],
        source_schema="products_catalog",
        referent_schema="products_catalog",
    )
    op.create_foreign_key(
        "fk_products_source_id_tags",
        "products",
        "tags",
        ["source_id"],
        ["id"],
        source_schema="products_catalog",
        referent_schema="products_catalog",
    )
    op.drop_index(
        op.f("ix_products_catalog_products_source_id"),
        table_name="products",
        schema="products_catalog",
    )
    # op.execute(
    #     """
    #     INSERT INTO products_catalog.tags (id, name, author_id, author_role, description, created_at, updated_at, discarded, version, type)
    #     SELECT
    #         id,
    #         name,
    #         author_id,
    #         author_role,
    #         description,
    #         created_at,
    #         updated_at,
    #         discarded,
    #         version,
    #         'brand'
    #     FROM products_catalog.brands
    #     """
    # )
    # op.execute(
    #     """
    #     INSERT INTO products_catalog.tags (id, name, author_id, author_role, description, created_at, updated_at, discarded, version, type)
    #     SELECT
    #         id,
    #         name,
    #         author_id,
    #         author_role,
    #         description,
    #         created_at,
    #         updated_at,
    #         discarded,
    #         version,
    #         'source'
    #     FROM products_catalog.sources
    #     """
    # )
    # op.execute(
    #     """
    #     DELETE FROM products_catalog.brands
    #     """
    # )
    # op.execute(
    #     """
    #     DELETE FROM products_catalog.sources
    #     """
    # )
    # ### end Alembic commands ###
