"""recipe instructions is now just a string

Revision ID: aa246f44ae83
Revises: 2d51a015f6a9
Create Date: 2024-05-08 14:43:09.411571

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "aa246f44ae83"
down_revision = "2d51a015f6a9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recipes",
        sa.Column("instructions", sa.String(), nullable=False),
        schema="recipes_catalog",
    )
    op.drop_table("instructions", schema="recipes_catalog")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instructions",
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("instruction", sa.String(), nullable=False),
        sa.Column("recipe_id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes_catalog.recipes.id"],
            name=op.f("fk_instructions_recipe_id_recipes"),
        ),
        sa.PrimaryKeyConstraint("number", "recipe_id", name=op.f("pk_instructions")),
        schema="recipes_catalog",
    )
    op.drop_column("recipes", "instructions", schema="recipes_catalog")
    # ### end Alembic commands ###
