"""add missing recipes_diet_types_association

Revision ID: b68587e33b73
Revises: 21c419b0b4a7
Create Date: 2024-06-16 20:11:10.408392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68587e33b73'
down_revision = '21c419b0b4a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes_diet_types_association',
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('diet_type_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['diet_type_id'], ['shared_kernel.diet_types.id'], name=op.f('fk_recipes_diet_types_association_diet_type_id_diet_types')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes_catalog.recipes.id'], name=op.f('fk_recipes_diet_types_association_recipe_id_recipes')),
    sa.PrimaryKeyConstraint('recipe_id', 'diet_type_id', name=op.f('pk_recipes_diet_types_association')),
    schema='recipes_catalog'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes_diet_types_association', schema='recipes_catalog')
    # ### end Alembic commands ###
