"""add season to meals

Revision ID: ba0a43b2c8d7
Revises: ed504305f201
Create Date: 2024-11-08 17:02:16.790127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba0a43b2c8d7'
down_revision = 'ed504305f201'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meals_season_association',
    sa.Column('meal_id', sa.String(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['recipes_catalog.meals.id'], name=op.f('fk_meals_season_association_meal_id_meals')),
    sa.ForeignKeyConstraint(['season_id'], ['recipes_catalog.months.id'], name=op.f('fk_meals_season_association_season_id_months')),
    sa.PrimaryKeyConstraint('meal_id', 'season_id', name=op.f('pk_meals_season_association')),
    schema='recipes_catalog'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meals_season_association', schema='recipes_catalog')
    # ### end Alembic commands ###
