"""add onboarding data to recipes catalog client

Revision ID: c0a08369503c
Revises: b7f3c4d5e8a1
Create Date: 2025-08-07 15:54:32.704586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c0a08369503c'
down_revision = 'b7f3c4d5e8a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('onboarding_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='recipes_catalog')
    op.alter_column('recipes', 'meal_id',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='recipes_catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'meal_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='recipes_catalog')
    op.drop_column('clients', 'onboarding_data', schema='recipes_catalog')
    # ### end Alembic commands ###
