"""add shopping list columns to products table

Revision ID: d9a08a44aa8e
Revises: 915b9d66978e
Create Date: 2025-05-07 14:15:08.369177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9a08a44aa8e'
down_revision = '915b9d66978e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('shopping_name', sa.String(), nullable=True), schema='products_catalog')
    op.add_column('products', sa.Column('store_department_name', sa.String(), nullable=True), schema='products_catalog')
    op.add_column('products', sa.Column('recommended_brands_and_products', sa.String(), nullable=True), schema='products_catalog')
    op.add_column('products', sa.Column('storable', sa.Boolean(), nullable=True), schema='products_catalog')
    op.add_column('products', sa.Column('edible_yield', sa.Numeric(precision=5, scale=4), nullable=True), schema='products_catalog')
    op.alter_column('meals', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='recipes_catalog')
    op.alter_column('menu_meals', 'meal_id',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='recipes_catalog')
    op.alter_column('recipes', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='recipes_catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='recipes_catalog')
    op.alter_column('menu_meals', 'meal_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='recipes_catalog')
    op.alter_column('meals', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='recipes_catalog')
    op.drop_column('products', 'edible_yield', schema='products_catalog')
    op.drop_column('products', 'storable', schema='products_catalog')
    op.drop_column('products', 'recommended_brands_and_products', schema='products_catalog')
    op.drop_column('products', 'store_department_name', schema='products_catalog')
    op.drop_column('products', 'shopping_name', schema='products_catalog')
    # ### end Alembic commands ###
