"""add meal_id to recipe

Revision ID: fa62c389a034
Revises: 3ac3e499d9a7
Create Date: 2024-11-02 19:57:04.587220

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fa62c389a034"
down_revision = "3ac3e499d9a7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meals",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("preprocessed_name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("author_id", sa.String(), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("discarded", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meals")),
        schema="recipes_catalog",
    )
    op.create_index(
        "ix_recipes_catalog_meals_preprocessed_name_gin_trgm",
        "meals",
        ["preprocessed_name"],
        unique=False,
        schema="recipes_catalog",
        postgresql_ops={"preprocessed_name": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.add_column(
        "recipes",
        sa.Column("meal_id", sa.String(), nullable=True),
        schema="recipes_catalog",
    )
    op.create_foreign_key(
        op.f("fk_recipes_meal_id_meals"),
        "recipes",
        "meals",
        ["meal_id"],
        ["id"],
        source_schema="recipes_catalog",
        referent_schema="recipes_catalog",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_recipes_meal_id_meals"),
        "recipes",
        schema="recipes_catalog",
        type_="foreignkey",
    )
    op.drop_column("recipes", "meal_id", schema="recipes_catalog")
    op.drop_index(
        "ix_recipes_catalog_recipes_preprocessed_name_gin_trgm",
        table_name="meals",
        schema="recipes_catalog",
        postgresql_ops={"preprocessed_name": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_table("meals", schema="recipes_catalog")
    # ### end Alembic commands ###
