"""add position to ingredients table

Revision ID: fbe187edafef
Revises: 55d8d6b3eaa7
Create Date: 2024-11-29 11:50:52.646489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbe187edafef'
down_revision = '55d8d6b3eaa7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('position', sa.Integer(), nullable=False), schema='recipes_catalog')
    op.create_unique_constraint('uq_recipes_catalog_ingredients_recipe_id_position', 'ingredients', ['recipe_id', 'position'], schema='recipes_catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_recipes_catalog_ingredients_recipe_id_position', 'ingredients', schema='recipes_catalog', type_='unique')
    op.drop_column('ingredients', 'position', schema='recipes_catalog')
    # ### end Alembic commands ###
