maizena = {
    "_id": "7894000010014",
    "_keywords": [
        "alimento",
        "almidon",
        "almidone",
        "amido",
        "bebida",
        "brasil",
        "cereale",
        "contiene",
        "de",
        "derivado",
        "duryea",
        "gluten",
        "maiz",
        "maizena",
        "milho",
        "omg",
        "origen",
        "patata",
        "sin",
        "unilever",
        "vegetal",
    ],
    "added_countries_tags": [],
    "additives_n": 0,
    "additives_original_tags": [],
    "additives_tags": [],
    "allergens": "",
    "allergens_from_ingredients": "",
    "allergens_from_user": "(es) ",
    "allergens_hierarchy": [],
    "allergens_lc": "es",
    "allergens_tags": [],
    "amino_acids_prev_tags": [],
    "amino_acids_tags": [],
    "brands": "Duryea,Maizena,Unilever",
    "brands_tags": ["duryea", "maizena", "unilever"],
    "categories": "Alimentos y bebidas de origen vegetal,Alimentos de origen vegetal,Cereales y patatas,Cereales y derivados,Almidones,Almidones de cereales,Almidón de maíz",
    "categories_hierarchy": [
        "en:plant-based-foods-and-beverages",
        "en:plant-based-foods",
        "en:cereals-and-potatoes",
        "en:cereals-and-their-products",
        "en:starches",
        "en:cereal-starches",
        "en:corn-starch",
    ],
    "categories_lc": "es",
    "categories_old": "Alimentos e bebidas à base de plantas, Alimentos à base de plantas, Cereais e Batatas, Cereais e seus produtos, en:Starches, en:Cereal starches, Amido de milho",
    "categories_properties": {
        "agribalyse_food_code:en": "9510",
        "ciqual_food_code:en": "9510",
    },
    "categories_properties_tags": [
        "all-products",
        "categories-known",
        "agribalyse-food-code-9510",
        "agribalyse-food-code-known",
        "agribalyse-proxy-food-code-unknown",
        "ciqual-food-code-9510",
        "ciqual-food-code-known",
        "agribalyse-known",
        "agribalyse-9510",
    ],
    "categories_tags": [
        "en:plant-based-foods-and-beverages",
        "en:plant-based-foods",
        "en:cereals-and-potatoes",
        "en:cereals-and-their-products",
        "en:starches",
        "en:cereal-starches",
        "en:corn-starch",
    ],
    "category_properties": {},
    "checkers_tags": [],
    "ciqual_food_name_tags": ["unknown"],
    "cities_tags": [],
    "code": "7894000010014",
    "codes_tags": [
        "code-13",
        "7894000010xxx",
        "789400001xxxx",
        "78940000xxxxx",
        "7894000xxxxxx",
        "789400xxxxxxx",
        "78940xxxxxxxx",
        "7894xxxxxxxxx",
        "789xxxxxxxxxx",
        "78xxxxxxxxxxx",
        "7xxxxxxxxxxxx",
    ],
    "compared_to_category": "en:corn-starch",
    "complete": 0,
    "completeness": 0.9625,
    "correctors_tags": ["openfoodfacts-contributors", "5m4u9"],
    "countries": "Bolivia,Brasil",
    "countries_hierarchy": ["en:bolivia", "en:brazil"],
    "countries_lc": "es",
    "countries_tags": ["en:bolivia", "en:brazil"],
    "created_t": 1534644104,
    "creator": "openfoodfacts-contributors",
    "data_quality_bugs_tags": [],
    "data_quality_errors_tags": [],
    "data_quality_info_tags": [
        "en:packaging-data-incomplete",
        "en:ingredients-percent-analysis-ok",
        "en:all-but-one-ingredient-with-specified-percent",
        "en:food-groups-1-known",
        "en:food-groups-2-known",
        "en:food-groups-3-unknown",
    ],
    "data_quality_tags": [
        "en:packaging-data-incomplete",
        "en:ingredients-percent-analysis-ok",
        "en:all-but-one-ingredient-with-specified-percent",
        "en:food-groups-1-known",
        "en:food-groups-2-known",
        "en:food-groups-3-unknown",
        "en:environmental-score-production-system-no-label",
    ],
    "data_quality_warnings_tags": ["en:environmental-score-production-system-no-label"],
    "debug_param_sorted_langs": ["pt", "es"],
    "ecoscore_data": {
        "adjustments": {
            "origins_of_ingredients": {
                "aggregated_origins": [
                    {
                        "epi_score": 13,
                        "origin": "en:brazil",
                        "percent": 100,
                        "transportation_score": 0,
                    }
                ],
                "epi_score": 13,
                "epi_value": -4,
                "origins_from_categories": ["en:unknown"],
                "origins_from_origins_field": ["en:brazil"],
                "transportation_score": 0,
                "transportation_scores": {
                    "ad": 0,
                    "al": 0,
                    "at": 0,
                    "ax": 0,
                    "ba": 0,
                    "be": 0,
                    "bg": 0,
                    "ch": 0,
                    "cy": 0,
                    "cz": 0,
                    "de": 0,
                    "dk": 0,
                    "dz": 0,
                    "ee": 0,
                    "eg": 0,
                    "es": 0,
                    "fi": 0,
                    "fo": 0,
                    "fr": 0,
                    "gg": 0,
                    "gi": 0,
                    "gr": 0,
                    "hr": 0,
                    "hu": 0,
                    "ie": 0,
                    "il": 0,
                    "im": 0,
                    "is": 0,
                    "it": 0,
                    "je": 0,
                    "lb": 0,
                    "li": 0,
                    "lt": 0,
                    "lu": 0,
                    "lv": 0,
                    "ly": 0,
                    "ma": 0,
                    "mc": 0,
                    "md": 0,
                    "me": 0,
                    "mk": 0,
                    "mt": 0,
                    "nl": 0,
                    "no": 0,
                    "pl": 0,
                    "ps": 0,
                    "pt": 0,
                    "ro": 0,
                    "rs": 0,
                    "se": 0,
                    "si": 0,
                    "sj": 0,
                    "sk": 0,
                    "sm": 0,
                    "sy": 0,
                    "tn": 0,
                    "tr": 0,
                    "ua": 0,
                    "uk": 0,
                    "us": 0,
                    "va": 0,
                    "world": 0,
                    "xk": 0,
                },
                "transportation_value": 0,
                "transportation_values": {
                    "ad": 0,
                    "al": 0,
                    "at": 0,
                    "ax": 0,
                    "ba": 0,
                    "be": 0,
                    "bg": 0,
                    "ch": 0,
                    "cy": 0,
                    "cz": 0,
                    "de": 0,
                    "dk": 0,
                    "dz": 0,
                    "ee": 0,
                    "eg": 0,
                    "es": 0,
                    "fi": 0,
                    "fo": 0,
                    "fr": 0,
                    "gg": 0,
                    "gi": 0,
                    "gr": 0,
                    "hr": 0,
                    "hu": 0,
                    "ie": 0,
                    "il": 0,
                    "im": 0,
                    "is": 0,
                    "it": 0,
                    "je": 0,
                    "lb": 0,
                    "li": 0,
                    "lt": 0,
                    "lu": 0,
                    "lv": 0,
                    "ly": 0,
                    "ma": 0,
                    "mc": 0,
                    "md": 0,
                    "me": 0,
                    "mk": 0,
                    "mt": 0,
                    "nl": 0,
                    "no": 0,
                    "pl": 0,
                    "ps": 0,
                    "pt": 0,
                    "ro": 0,
                    "rs": 0,
                    "se": 0,
                    "si": 0,
                    "sj": 0,
                    "sk": 0,
                    "sm": 0,
                    "sy": 0,
                    "tn": 0,
                    "tr": 0,
                    "ua": 0,
                    "uk": 0,
                    "us": 0,
                    "va": 0,
                    "world": 0,
                    "xk": 0,
                },
                "value": -4,
                "values": {
                    "ad": -4,
                    "al": -4,
                    "at": -4,
                    "ax": -4,
                    "ba": -4,
                    "be": -4,
                    "bg": -4,
                    "ch": -4,
                    "cy": -4,
                    "cz": -4,
                    "de": -4,
                    "dk": -4,
                    "dz": -4,
                    "ee": -4,
                    "eg": -4,
                    "es": -4,
                    "fi": -4,
                    "fo": -4,
                    "fr": -4,
                    "gg": -4,
                    "gi": -4,
                    "gr": -4,
                    "hr": -4,
                    "hu": -4,
                    "ie": -4,
                    "il": -4,
                    "im": -4,
                    "is": -4,
                    "it": -4,
                    "je": -4,
                    "lb": -4,
                    "li": -4,
                    "lt": -4,
                    "lu": -4,
                    "lv": -4,
                    "ly": -4,
                    "ma": -4,
                    "mc": -4,
                    "md": -4,
                    "me": -4,
                    "mk": -4,
                    "mt": -4,
                    "nl": -4,
                    "no": -4,
                    "pl": -4,
                    "ps": -4,
                    "pt": -4,
                    "ro": -4,
                    "rs": -4,
                    "se": -4,
                    "si": -4,
                    "sj": -4,
                    "sk": -4,
                    "sm": -4,
                    "sy": -4,
                    "tn": -4,
                    "tr": -4,
                    "ua": -4,
                    "uk": -4,
                    "us": -4,
                    "va": -4,
                    "world": -4,
                    "xk": -4,
                },
            },
            "packaging": {
                "non_recyclable_and_non_biodegradable_materials": 1,
                "packagings": [
                    {
                        "environmental_score_material_score": 92,
                        "environmental_score_shape_ratio": 1,
                        "material": "en:paperboard",
                        "number_of_units": 1,
                        "quantity_per_unit": "200 g",
                        "quantity_per_unit_unit": "g",
                        "quantity_per_unit_value": 200,
                        "shape": "en:box",
                    },
                    {
                        "environmental_score_material_score": 0,
                        "environmental_score_shape_ratio": 1,
                        "material": "en:plastic",
                        "non_recyclable_and_non_biodegradable": "maybe",
                        "number_of_units": 1,
                        "quantity_per_unit": "200 g",
                        "quantity_per_unit_unit": "g",
                        "quantity_per_unit_value": 200,
                        "shape": "en:bag",
                    },
                ],
                "score": -8,
                "value": -11,
            },
            "production_system": {"labels": [], "value": 0, "warning": "no_label"},
            "threatened_species": {},
        },
        "agribalyse": {
            "agribalyse_food_code": "9510",
            "co2_agriculture": 0,
            "co2_consumption": 0,
            "co2_distribution": 0.026758057,
            "co2_packaging": 0.10086321,
            "co2_processing": 0.84583517,
            "co2_total": 1.081967347,
            "co2_transportation": 0.10851091,
            "code": "9510",
            "dqr": "3.16",
            "ef_agriculture": 0,
            "ef_consumption": 0,
            "ef_distribution": 0.0076076094,
            "ef_packaging": 0.010016176,
            "ef_processing": 0.1418827,
            "ef_total": 0.1681118001,
            "ef_transportation": 0.0086053147,
            "is_beverage": 0,
            "name_en": "Maize/corn starch",
            "name_fr": "Amidon de maïs ou fécule de maïs",
            "score": 93,
            "version": "3.1.1",
        },
        "grade": "a",
        "grades": {
            "ad": "a",
            "al": "a",
            "at": "a",
            "ax": "a",
            "ba": "a",
            "be": "a",
            "bg": "a",
            "ch": "a",
            "cy": "a",
            "cz": "a",
            "de": "a",
            "dk": "a",
            "dz": "a",
            "ee": "a",
            "eg": "a",
            "es": "a",
            "fi": "a",
            "fo": "a",
            "fr": "a",
            "gg": "a",
            "gi": "a",
            "gr": "a",
            "hr": "a",
            "hu": "a",
            "ie": "a",
            "il": "a",
            "im": "a",
            "is": "a",
            "it": "a",
            "je": "a",
            "lb": "a",
            "li": "a",
            "lt": "a",
            "lu": "a",
            "lv": "a",
            "ly": "a",
            "ma": "a",
            "mc": "a",
            "md": "a",
            "me": "a",
            "mk": "a",
            "mt": "a",
            "nl": "a",
            "no": "a",
            "pl": "a",
            "ps": "a",
            "pt": "a",
            "ro": "a",
            "rs": "a",
            "se": "a",
            "si": "a",
            "sj": "a",
            "sk": "a",
            "sm": "a",
            "sy": "a",
            "tn": "a",
            "tr": "a",
            "ua": "a",
            "uk": "a",
            "us": "a",
            "va": "a",
            "world": "a",
            "xk": "a",
        },
        "missing": {"labels": 1},
        "missing_data_warning": 1,
        "previous_data": {
            "agribalyse": {"warning": "missing_agribalyse_match"},
            "grade": None,
            "score": None,
        },
        "score": 78,
        "scores": {
            "ad": 78,
            "al": 78,
            "at": 78,
            "ax": 78,
            "ba": 78,
            "be": 78,
            "bg": 78,
            "ch": 78,
            "cy": 78,
            "cz": 78,
            "de": 78,
            "dk": 78,
            "dz": 78,
            "ee": 78,
            "eg": 78,
            "es": 78,
            "fi": 78,
            "fo": 78,
            "fr": 78,
            "gg": 78,
            "gi": 78,
            "gr": 78,
            "hr": 78,
            "hu": 78,
            "ie": 78,
            "il": 78,
            "im": 78,
            "is": 78,
            "it": 78,
            "je": 78,
            "lb": 78,
            "li": 78,
            "lt": 78,
            "lu": 78,
            "lv": 78,
            "ly": 78,
            "ma": 78,
            "mc": 78,
            "md": 78,
            "me": 78,
            "mk": 78,
            "mt": 78,
            "nl": 78,
            "no": 78,
            "pl": 78,
            "ps": 78,
            "pt": 78,
            "ro": 78,
            "rs": 78,
            "se": 78,
            "si": 78,
            "sj": 78,
            "sk": 78,
            "sm": 78,
            "sy": 78,
            "tn": 78,
            "tr": 78,
            "ua": 78,
            "uk": 78,
            "us": 78,
            "va": 78,
            "world": 78,
            "xk": 78,
        },
        "status": "known",
    },
    "ecoscore_grade": "a",
    "ecoscore_score": 78,
    "ecoscore_tags": ["a"],
    "editors_tags": ["5m4u9", "foodless", "openfoodfacts-contributors"],
    "emb_codes": "CNPJ 01615814/0044-33",
    "emb_codes_tags": ["cnpj-01615814-0044-33"],
    "entry_dates_tags": ["2018-08-19", "2018-08", "2018"],
    "expiration_date": "",
    "food_groups": "en:cereals",
    "food_groups_tags": ["en:cereals-and-potatoes", "en:cereals"],
    "generic_name": "amido de milho.",
    "generic_name_en": "",
    "generic_name_es": "almidón de maíz.",
    "generic_name_pt": "amido de milho.",
    "id": "7894000010014",
    "image_front_small_url": "https://images.openfoodfacts.org/images/products/789/400/001/0014/front_pt.5.200.jpg",
    "image_front_thumb_url": "https://images.openfoodfacts.org/images/products/789/400/001/0014/front_pt.5.100.jpg",
    "image_front_url": "https://images.openfoodfacts.org/images/products/789/400/001/0014/front_pt.5.400.jpg",
    "image_small_url": "https://images.openfoodfacts.org/images/products/789/400/001/0014/front_pt.5.200.jpg",
    "image_thumb_url": "https://images.openfoodfacts.org/images/products/789/400/001/0014/front_pt.5.100.jpg",
    "image_url": "https://images.openfoodfacts.org/images/products/789/400/001/0014/front_pt.5.400.jpg",
    "images": {
        "1": {
            "sizes": {
                "100": {"h": 100, "w": 63},
                "400": {"h": 400, "w": 253},
                "full": {"h": 3695, "w": 2336},
            },
            "uploaded_t": 1534644104,
            "uploader": "openfoodfacts-contributors",
        },
        "front_es": {
            "imgid": "1",
            "rev": "6",
            "sizes": {
                "100": {"h": 100, "w": 63},
                "200": {"h": 200, "w": 126},
                "400": {"h": 400, "w": 253},
                "full": {"h": 3695, "w": 2336},
            },
        },
        "front_pt": {
            "imgid": "1",
            "rev": "5",
            "sizes": {
                "100": {"h": 100, "w": 63},
                "200": {"h": 200, "w": 126},
                "400": {"h": 400, "w": 253},
                "full": {"h": 3695, "w": 2336},
            },
        },
    },
    "informers_tags": ["openfoodfacts-contributors", "5m4u9"],
    "ingredients": [
        {
            "ciqual_proxy_food_code": "9510",
            "id": "en:starch",
            "is_in_taxonomy": 1,
            "percent_estimate": 100,
            "percent_max": 100,
            "percent_min": 100,
            "text": "AMIDO",
            "vegan": "yes",
            "vegetarian": "yes",
        }
    ],
    "ingredients_analysis": {},
    "ingredients_analysis_tags": ["en:palm-oil-free", "en:vegan", "en:vegetarian"],
    "ingredients_debug": [],
    "ingredients_from_or_that_may_be_from_palm_oil_n": 0,
    "ingredients_from_palm_oil_n": 0,
    "ingredients_from_palm_oil_tags": [],
    "ingredients_hierarchy": ["en:starch"],
    "ingredients_ids_debug": [],
    "ingredients_lc": "pt",
    "ingredients_n": 1,
    "ingredients_n_tags": ["1", "1-10"],
    "ingredients_non_nutritive_sweeteners_n": 0,
    "ingredients_original_tags": ["en:starch"],
    "ingredients_percent_analysis": 1,
    "ingredients_sweeteners_n": 0,
    "ingredients_tags": ["en:starch"],
    "ingredients_text": "AMIDO.",
    "ingredients_text_en": "",
    "ingredients_text_es": "",
    "ingredients_text_pt": "AMIDO.",
    "ingredients_text_with_allergens": "AMIDO.",
    "ingredients_text_with_allergens_es": "",
    "ingredients_text_with_allergens_pt": "AMIDO.",
    "ingredients_that_may_be_from_palm_oil_n": 0,
    "ingredients_that_may_be_from_palm_oil_tags": [],
    "ingredients_with_specified_percent_n": 0,
    "ingredients_with_specified_percent_sum": 0,
    "ingredients_with_unspecified_percent_n": 1,
    "ingredients_with_unspecified_percent_sum": 100,
    "ingredients_without_ciqual_codes": [],
    "ingredients_without_ciqual_codes_n": 0,
    "ingredients_without_ecobalyse_ids": ["en:starch"],
    "ingredients_without_ecobalyse_ids_n": 1,
    "interface_version_created": "20120622",
    "interface_version_modified": "20150316.jqm2",
    "known_ingredients_n": 1,
    "labels": "Sin gluten,Contiene OMG",
    "labels_hierarchy": ["en:no-gluten", "en:contains-gmos"],
    "labels_lc": "es",
    "labels_old": "Sin gluten,Contiene OMG",
    "labels_tags": ["en:no-gluten", "en:contains-gmos"],
    "lang": "pt",
    "languages": {"en:portuguese": 4, "en:spanish": 3},
    "languages_codes": {"es": 3, "pt": 4},
    "languages_hierarchy": ["en:portuguese", "en:spanish"],
    "languages_tags": ["en:portuguese", "en:spanish", "en:2", "en:multilingual"],
    "last_edit_dates_tags": ["2025-08-24", "2025-08", "2025"],
    "last_editor": "foodless",
    "last_image_dates_tags": ["2018-08-19", "2018-08", "2018"],
    "last_image_t": 1534644106,
    "last_modified_by": "foodless",
    "last_modified_t": 1756043545,
    "last_updated_t": 1756043545,
    "lc": "pt",
    "link": "",
    "main_countries_tags": [],
    "manufacturing_places": "Brasil",
    "manufacturing_places_tags": ["brasil"],
    "max_imgid": "1",
    "minerals_prev_tags": [],
    "minerals_tags": [],
    "misc_tags": [
        "en:environmental-score-changed",
        "en:environmental-score-computed",
        "en:environmental-score-grade-changed",
        "en:environmental-score-missing-data-labels",
        "en:environmental-score-missing-data-warning",
        "en:nutriscore-2021-c-2023-c",
        "en:nutriscore-2021-same-as-2023",
        "en:nutriscore-computed",
        "en:nutrition-all-nutriscore-values-known",
        "en:nutrition-fruits-vegetables-legumes-estimate-from-ingredients",
        "en:nutrition-fruits-vegetables-nuts-estimate-from-ingredients",
        "en:packagings-complete",
        "en:packagings-not-empty",
        "en:packagings-number-of-components-2",
        "en:main-countries-bo-ingredients-not-in-country-language",
    ],
    "no_nutrition_data": "",
    "nova_group": 2,
    "nova_group_debug": "",
    "nova_groups": "2",
    "nova_groups_markers": {"2": [["categories", "en:starches"]]},
    "nova_groups_tags": ["en:2-processed-culinary-ingredients"],
    "nucleotides_prev_tags": [],
    "nucleotides_tags": [],
    "nutrient_levels": {
        "fat": "low",
        "salt": "low",
        "saturated-fat": "low",
        "sugars": "low",
    },
    "nutrient_levels_tags": [
        "en:fat-in-low-quantity",
        "en:saturated-fat-in-low-quantity",
        "en:sugars-in-low-quantity",
        "en:salt-in-low-quantity",
    ],
    "nutriments": {
        "carbohydrates": 17,
        "carbohydrates_100g": 85,
        "carbohydrates_serving": 17,
        "carbohydrates_unit": "g",
        "carbohydrates_value": 17,
        "energy": 293,
        "energy-kcal": 70,
        "energy-kcal_100g": 350,
        "energy-kcal_serving": 70,
        "energy-kcal_unit": "kcal",
        "energy-kcal_value": 70,
        "energy-kcal_value_computed": 68,
        "energy_100g": 1460,
        "energy_serving": 293,
        "energy_unit": "kcal",
        "energy_value": 70,
        "fat": 0,
        "fat_100g": 0,
        "fat_serving": 0,
        "fat_unit": "g",
        "fat_value": 0,
        "fiber": 0,
        "fiber_100g": 0,
        "fiber_serving": 0,
        "fiber_unit": "g",
        "fiber_value": 0,
        "fruits-vegetables-legumes-estimate-from-ingredients_100g": 0,
        "fruits-vegetables-legumes-estimate-from-ingredients_serving": 0,
        "fruits-vegetables-nuts-estimate-from-ingredients_100g": 0,
        "fruits-vegetables-nuts-estimate-from-ingredients_serving": 0,
        "nova-group": 2,
        "nova-group_100g": 2,
        "nova-group_serving": 2,
        "nutrition-score-fr": 4,
        "nutrition-score-fr_100g": 4,
        "proteins": 0,
        "proteins_100g": 0,
        "proteins_serving": 0,
        "proteins_unit": "g",
        "proteins_value": 0,
        "salt": 0,
        "salt_100g": 0,
        "salt_serving": 0,
        "salt_unit": "mg",
        "salt_value": 0,
        "saturated-fat": 0,
        "saturated-fat_100g": 0,
        "saturated-fat_serving": 0,
        "saturated-fat_unit": "g",
        "saturated-fat_value": 0,
        "sodium": 0,
        "sodium_100g": 0,
        "sodium_serving": 0,
        "sodium_unit": "mg",
        "sodium_value": 0,
        "sugars": 0,
        "sugars_100g": 0,
        "sugars_serving": 0,
        "sugars_unit": "g",
        "sugars_value": 0,
        "trans-fat": 0,
        "trans-fat_100g": 0,
        "trans-fat_label": "Grasas trans",
        "trans-fat_serving": 0,
        "trans-fat_unit": "g",
        "trans-fat_value": 0,
    },
    "nutriments_estimated": {
        "alcohol_100g": 0,
        "beta-carotene_100g": 0,
        "calcium_100g": 0.006,
        "carbohydrates_100g": 89.2,
        "cholesterol_100g": 0,
        "copper_100g": 5e-05,
        "energy-kcal_100g": 362,
        "energy-kj_100g": 1540,
        "energy_100g": 1540,
        "fat_100g": 0.25,
        "fiber_100g": 0.8,
        "fructose_100g": 0,
        "galactose_100g": 0,
        "glucose_100g": 0,
        "iodine_100g": 6e-07,
        "iron_100g": 0.00038,
        "lactose_100g": 0,
        "magnesium_100g": 0.0035,
        "maltose_100g": 0,
        "manganese_100g": 0.00053,
        "pantothenic-acid_100g": 0,
        "phosphorus_100g": 0.056,
        "phylloquinone_100g": 0,
        "polyols_100g": 0,
        "potassium_100g": 0.004,
        "proteins_100g": 0.43,
        "salt_100g": 0.019,
        "saturated-fat_100g": 0.009,
        "selenium_100g": 2.8e-06,
        "sodium_100g": 0.0102,
        "starch_100g": 87,
        "sucrose_100g": 0,
        "sugars_100g": 0,
        "vitamin-a_100g": 0,
        "vitamin-b12_100g": 0,
        "vitamin-b1_100g": 0,
        "vitamin-b2_100g": 8e-06,
        "vitamin-b6_100g": 5e-06,
        "vitamin-b9_100g": 1e-06,
        "vitamin-c_100g": 0,
        "vitamin-d_100g": 0,
        "vitamin-e_100g": 0,
        "vitamin-pp_100g": 3e-05,
        "water_100g": 9.26,
        "zinc_100g": 0.00028,
    },
    "nutriscore": {
        "2021": {
            "category_available": 1,
            "data": {
                "energy": 1460,
                "energy_points": 4,
                "energy_value": 1460,
                "fiber": 0,
                "fiber_points": 0,
                "fiber_value": 0,
                "fruits_vegetables_nuts_colza_walnut_olive_oils": 0,
                "fruits_vegetables_nuts_colza_walnut_olive_oils_points": 0,
                "fruits_vegetables_nuts_colza_walnut_olive_oils_value": 0,
                "is_beverage": 0,
                "is_cheese": 0,
                "is_fat": 0,
                "is_water": 0,
                "negative_points": 4,
                "positive_points": 0,
                "proteins": 0,
                "proteins_points": 0,
                "proteins_value": 0,
                "saturated_fat": 0,
                "saturated_fat_points": 0,
                "saturated_fat_value": 0,
                "sodium": 0,
                "sodium_points": 0,
                "sodium_value": 0,
                "sugars": 0,
                "sugars_points": 0,
                "sugars_value": 0,
            },
            "grade": "c",
            "nutrients_available": 1,
            "nutriscore_applicable": 1,
            "nutriscore_computed": 1,
            "score": 4,
        },
        "2023": {
            "category_available": 1,
            "data": {
                "components": {
                    "negative": [
                        {
                            "id": "energy",
                            "points": 4,
                            "points_max": 10,
                            "unit": "kJ",
                            "value": 1460,
                        },
                        {
                            "id": "sugars",
                            "points": 0,
                            "points_max": 15,
                            "unit": "g",
                            "value": 0,
                        },
                        {
                            "id": "saturated_fat",
                            "points": 0,
                            "points_max": 10,
                            "unit": "g",
                            "value": 0,
                        },
                        {
                            "id": "salt",
                            "points": 0,
                            "points_max": 20,
                            "unit": "g",
                            "value": 0,
                        },
                    ],
                    "positive": [
                        {
                            "id": "proteins",
                            "points": 0,
                            "points_max": 7,
                            "unit": "g",
                            "value": 0,
                        },
                        {
                            "id": "fiber",
                            "points": 0,
                            "points_max": 5,
                            "unit": "g",
                            "value": 0,
                        },
                        {
                            "id": "fruits_vegetables_legumes",
                            "points": 0,
                            "points_max": 5,
                            "unit": "%",
                            "value": 0,
                        },
                    ],
                },
                "count_proteins": 1,
                "count_proteins_reason": "negative_points_less_than_11",
                "is_beverage": 0,
                "is_cheese": 0,
                "is_fat_oil_nuts_seeds": 0,
                "is_red_meat_product": 0,
                "is_water": 0,
                "negative_points": 4,
                "negative_points_max": 55,
                "positive_nutrients": [
                    "proteins",
                    "fiber",
                    "fruits_vegetables_legumes",
                ],
                "positive_points": 0,
                "positive_points_max": 17,
            },
            "grade": "c",
            "nutrients_available": 1,
            "nutriscore_applicable": 1,
            "nutriscore_computed": 1,
            "score": 4,
        },
    },
    "nutriscore_2021_tags": ["c"],
    "nutriscore_2023_tags": ["c"],
    "nutriscore_data": {
        "components": {
            "negative": [
                {
                    "id": "energy",
                    "points": 4,
                    "points_max": 10,
                    "unit": "kJ",
                    "value": 1460,
                },
                {
                    "id": "sugars",
                    "points": 0,
                    "points_max": 15,
                    "unit": "g",
                    "value": 0,
                },
                {
                    "id": "saturated_fat",
                    "points": 0,
                    "points_max": 10,
                    "unit": "g",
                    "value": 0,
                },
                {"id": "salt", "points": 0, "points_max": 20, "unit": "g", "value": 0},
            ],
            "positive": [
                {
                    "id": "proteins",
                    "points": 0,
                    "points_max": 7,
                    "unit": "g",
                    "value": 0,
                },
                {"id": "fiber", "points": 0, "points_max": 5, "unit": "g", "value": 0},
                {
                    "id": "fruits_vegetables_legumes",
                    "points": 0,
                    "points_max": 5,
                    "unit": "%",
                    "value": 0,
                },
            ],
        },
        "count_proteins": 1,
        "count_proteins_reason": "negative_points_less_than_11",
        "grade": "c",
        "is_beverage": 0,
        "is_cheese": 0,
        "is_fat_oil_nuts_seeds": 0,
        "is_red_meat_product": 0,
        "is_water": 0,
        "negative_points": 4,
        "negative_points_max": 55,
        "positive_nutrients": ["proteins", "fiber", "fruits_vegetables_legumes"],
        "positive_points": 0,
        "positive_points_max": 17,
        "score": 4,
    },
    "nutriscore_grade": "c",
    "nutriscore_score": 4,
    "nutriscore_score_opposite": -4,
    "nutriscore_tags": ["c"],
    "nutriscore_version": "2023",
    "nutrition_data": "on",
    "nutrition_data_per": "serving",
    "nutrition_data_prepared": "",
    "nutrition_data_prepared_per": "100g",
    "nutrition_grade_fr": "c",
    "nutrition_grades": "c",
    "nutrition_grades_tags": ["c"],
    "nutrition_score_beverage": 0,
    "nutrition_score_debug": "",
    "nutrition_score_warning_fruits_vegetables_legumes_estimate_from_ingredients": 1,
    "nutrition_score_warning_fruits_vegetables_legumes_estimate_from_ingredients_value": 0,
    "nutrition_score_warning_fruits_vegetables_nuts_estimate_from_ingredients": 1,
    "nutrition_score_warning_fruits_vegetables_nuts_estimate_from_ingredients_value": 0,
    "origin": "",
    "origin_en": "",
    "origin_es": "",
    "origin_pt": "",
    "origins": "Brasil",
    "origins_hierarchy": ["en:brazil"],
    "origins_lc": "es",
    "origins_tags": ["en:brazil"],
    "other_nutritional_substances_tags": [],
    "packaging": "Plástico,22 PAP,Bolsa,Caja",
    "packaging_hierarchy": ["en:plastic", "en:paper", "en:bag", "en:box"],
    "packaging_lc": "es",
    "packaging_materials_tags": ["en:paperboard", "en:plastic"],
    "packaging_recycling_tags": [],
    "packaging_shapes_tags": ["en:bag", "en:box"],
    "packaging_tags": ["en:plastic", "en:paper", "en:bag", "en:box"],
    "packaging_text": "",
    "packaging_text_en": "",
    "packaging_text_es": "",
    "packaging_text_pt": "",
    "packagings": [
        {
            "material": "en:paperboard",
            "number_of_units": 1,
            "quantity_per_unit": "200 g",
            "quantity_per_unit_unit": "g",
            "quantity_per_unit_value": 200,
            "shape": "en:box",
        },
        {
            "material": "en:plastic",
            "number_of_units": 1,
            "quantity_per_unit": "200 g",
            "quantity_per_unit_unit": "g",
            "quantity_per_unit_value": 200,
            "shape": "en:bag",
        },
    ],
    "packagings_complete": 1,
    "packagings_materials": {"all": {}, "en:paper-or-cardboard": {}, "en:plastic": {}},
    "packagings_n": 2,
    "photographers_tags": ["openfoodfacts-contributors"],
    "pnns_groups_1": "Cereals and potatoes",
    "pnns_groups_1_tags": ["cereals-and-potatoes", "known"],
    "pnns_groups_2": "Cereals",
    "pnns_groups_2_tags": ["cereals", "known"],
    "popularity_key": 2,
    "popularity_tags": [
        "at-least-5-scans-2020",
        "top-75-percent-scans-2020",
        "top-80-percent-scans-2020",
        "top-85-percent-scans-2020",
        "top-90-percent-scans-2020",
        "top-50-br-scans-2020",
        "top-100-br-scans-2020",
        "top-500-br-scans-2020",
        "top-1000-br-scans-2020",
        "top-5000-br-scans-2020",
        "top-10000-br-scans-2020",
        "top-50000-br-scans-2020",
        "top-100000-br-scans-2020",
        "top-country-br-scans-2020",
        "top-50000-de-scans-2020",
        "top-100000-de-scans-2020",
        "top-75-percent-scans-2021",
        "top-80-percent-scans-2021",
        "top-85-percent-scans-2021",
        "top-90-percent-scans-2021",
        "top-50-br-scans-2021",
        "top-100-br-scans-2021",
        "top-500-br-scans-2021",
        "top-1000-br-scans-2021",
        "top-5000-br-scans-2021",
        "top-10000-br-scans-2021",
        "top-50000-br-scans-2021",
        "top-100000-br-scans-2021",
        "top-country-br-scans-2021",
        "top-75-percent-scans-2022",
        "top-80-percent-scans-2022",
        "top-85-percent-scans-2022",
        "top-90-percent-scans-2022",
        "top-500-br-scans-2022",
        "top-1000-br-scans-2022",
        "top-5000-br-scans-2022",
        "top-10000-br-scans-2022",
        "top-50000-br-scans-2022",
        "top-100000-br-scans-2022",
        "top-country-br-scans-2022",
        "top-75-percent-scans-2023",
        "top-80-percent-scans-2023",
        "top-85-percent-scans-2023",
        "top-90-percent-scans-2023",
        "top-500-br-scans-2023",
        "top-1000-br-scans-2023",
        "top-5000-br-scans-2023",
        "top-10000-br-scans-2023",
        "top-50000-br-scans-2023",
        "top-100000-br-scans-2023",
        "top-country-br-scans-2023",
        "top-75-percent-scans-2024",
        "top-80-percent-scans-2024",
        "top-85-percent-scans-2024",
        "top-90-percent-scans-2024",
        "top-5000-br-scans-2024",
        "top-10000-br-scans-2024",
        "top-50000-br-scans-2024",
        "top-100000-br-scans-2024",
        "top-country-br-scans-2024",
        "top-100-py-scans-2024",
        "top-500-py-scans-2024",
        "top-1000-py-scans-2024",
        "top-5000-py-scans-2024",
        "top-10000-py-scans-2024",
        "top-50000-py-scans-2024",
        "top-100000-py-scans-2024",
    ],
    "product_name": "Maizena",
    "product_name_en": "",
    "product_name_es": "Maizena",
    "product_name_pt": "Maizena",
    "product_quantity": "200",
    "product_quantity_unit": "g",
    "product_type": "food",
    "purchase_places": "",
    "purchase_places_tags": [],
    "quantity": "200 g",
    "removed_countries_tags": [],
    "rev": 18,
    "scans_n": 2,
    "schema_version": 998,
    "selected_images": {
        "front": {
            "display": {
                "es": "https://images.openfoodfacts.org/images/products/789/400/001/0014/front_es.6.400.jpg",
                "pt": "https://images.openfoodfacts.org/images/products/789/400/001/0014/front_pt.5.400.jpg",
            },
            "small": {
                "es": "https://images.openfoodfacts.org/images/products/789/400/001/0014/front_es.6.200.jpg",
                "pt": "https://images.openfoodfacts.org/images/products/789/400/001/0014/front_pt.5.200.jpg",
            },
            "thumb": {
                "es": "https://images.openfoodfacts.org/images/products/789/400/001/0014/front_es.6.100.jpg",
                "pt": "https://images.openfoodfacts.org/images/products/789/400/001/0014/front_pt.5.100.jpg",
            },
        }
    },
    "serving_quantity": "20",
    "serving_quantity_unit": "g",
    "serving_size": "1 colher/cuchara (20 g)",
    "sortkey": 1534644108,
    "states": "en:to-be-completed, en:nutrition-facts-completed, en:ingredients-completed, en:expiration-date-to-be-completed, en:packaging-code-completed, en:characteristics-completed, en:origins-completed, en:categories-completed, en:brands-completed, en:packaging-completed, en:quantity-completed, en:product-name-completed, en:photos-to-be-validated, en:packaging-photo-to-be-selected, en:nutrition-photo-to-be-selected, en:ingredients-photo-to-be-selected, en:front-photo-selected, en:photos-uploaded",
    "states_hierarchy": [
        "en:to-be-completed",
        "en:nutrition-facts-completed",
        "en:ingredients-completed",
        "en:expiration-date-to-be-completed",
        "en:packaging-code-completed",
        "en:characteristics-completed",
        "en:origins-completed",
        "en:categories-completed",
        "en:brands-completed",
        "en:packaging-completed",
        "en:quantity-completed",
        "en:product-name-completed",
        "en:photos-to-be-validated",
        "en:packaging-photo-to-be-selected",
        "en:nutrition-photo-to-be-selected",
        "en:ingredients-photo-to-be-selected",
        "en:front-photo-selected",
        "en:photos-uploaded",
    ],
    "states_tags": [
        "en:to-be-completed",
        "en:nutrition-facts-completed",
        "en:ingredients-completed",
        "en:expiration-date-to-be-completed",
        "en:packaging-code-completed",
        "en:characteristics-completed",
        "en:origins-completed",
        "en:categories-completed",
        "en:brands-completed",
        "en:packaging-completed",
        "en:quantity-completed",
        "en:product-name-completed",
        "en:photos-to-be-validated",
        "en:packaging-photo-to-be-selected",
        "en:nutrition-photo-to-be-selected",
        "en:ingredients-photo-to-be-selected",
        "en:front-photo-selected",
        "en:photos-uploaded",
    ],
    "stores": "Farmacorp",
    "stores_tags": ["farmacorp"],
    "traces": "",
    "traces_from_ingredients": "",
    "traces_from_user": "(es) ",
    "traces_hierarchy": [],
    "traces_lc": "es",
    "traces_tags": [],
    "unique_scans_n": 2,
    "unknown_ingredients_n": 0,
    "unknown_nutrients_tags": [],
    "update_key": "sort",
    "vitamins_prev_tags": [],
    "vitamins_tags": [],
    "weighers_tags": [],
}
