[project]
name = "menu-planning-fastapi"
version = "0.1.0"
description = "Menu Planning API - FastAPI Runtime"
authors = [{ name = "Your Name", email = "your.email@example.com" }]
requires-python = ">=3.12,<3.13"
dependencies = [
    "dependency-injector>=4.41.0",
    "attrs>=25.1.0",
    "python-dotenv>=1.0.0",
    "python-multipart>=0.0.9",
    "Unidecode>=1.3.8",
    "asyncpg>=0.29.0",
    "yarl>=1.9.4",
    "anyio>=4.0.0",
    "colorlog>=6.8.0",
    "sqlalchemy>=2.0.25",
    "pydantic>=2.5.2",
    "pydantic-settings>=2.1.0",
    "python-json-logger>=3.2.1",
    "email-validator>=2.2.0",
    "greenlet>=3.1.1,<4.0.0",
    "structlog>=25.4.0,<26.0.0",
    "psutil>=7.0.0,<8.0.0",
    "fastapi>=0.116.2",
    "uvicorn>=0.32.1",
    "httpx>=0.28.1,<0.29.0",
    "starlette>=0.41.0",
    "pyjwt>=2.8.0",
    "cryptography>=41.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
