services:
  testdb:
    image: postgres:16-alpine
    # networks:
    #   - jenkins
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"

  mailhog:
    image: mailhog/mailhog:latest
    # networks:
    #   - jenkins
    ports:
      - "${SMTP_PORT}:1025"
      - "${SMTP_HTTP_PORT}:8025"

  rabbitmq:
    image: rabbitmq:3.12-management
    # networks:
    #   - jenkins
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_PORT}:15672"
# volumes:
#   test_results:
# networks:
#   jenkins:
#     external: true
