"""iam.users left only with columns id, roles, discarded and version

Revision ID: 1403b10e98e5
Revises: 0fcb6d02ae1c
Create Date: 2024-04-06 18:00:17.156223

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1403b10e98e5"
down_revision = "0fcb6d02ae1c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_iam_users_email", table_name="users", schema="iam")
    op.drop_index("ix_iam_users_username", table_name="users", schema="iam")
    op.drop_column("users", "hashed_password", schema="iam")
    op.drop_column("users", "active", schema="iam")
    op.drop_column("users", "confirmed", schema="iam")
    op.drop_column("users", "email", schema="iam")
    op.drop_column("users", "username", schema="iam")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False),
        schema="iam",
    )
    op.add_column(
        "users",
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        schema="iam",
    )
    op.add_column(
        "users",
        sa.Column("confirmed", sa.BOOLEAN(), autoincrement=False, nullable=False),
        schema="iam",
    )
    op.add_column(
        "users",
        sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        schema="iam",
    )
    op.add_column(
        "users",
        sa.Column("hashed_password", sa.VARCHAR(), autoincrement=False, nullable=False),
        schema="iam",
    )
    op.create_index(
        "ix_iam_users_username", "users", ["username"], unique=True, schema="iam"
    )
    op.create_index("ix_iam_users_email", "users", ["email"], unique=True, schema="iam")
    # ### end Alembic commands ###
