"""add weight_in_grams column to recipes_catalog.recipes table

Revision ID: 2e1e7b469cec
Revises: 00f7105350d4
Create Date: 2024-04-24 13:23:22.556254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e1e7b469cec'
down_revision = '00f7105350d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('weight_in_grams', sa.Float(), nullable=True), schema='recipes_catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'weight_in_grams', schema='recipes_catalog')
    # ### end Alembic commands ###
