"""create more indexes

Revision ID: 55d8d6b3eaa7
Revises: 635004bc0898
Create Date: 2024-11-08 17:27:41.675311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55d8d6b3eaa7'
down_revision = '635004bc0898'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_recipes_catalog_recipes_average_convenience_rating'), 'recipes', ['average_convenience_rating'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_recipes_average_taste_rating'), 'recipes', ['average_taste_rating'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_tags_author_id'), 'tags', ['author_id'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_tags_name'), 'tags', ['name'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_tags_privacy'), 'tags', ['privacy'], unique=False, schema='recipes_catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipes_catalog_tags_privacy'), table_name='tags', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_tags_name'), table_name='tags', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_tags_author_id'), table_name='tags', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_recipes_average_taste_rating'), table_name='recipes', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_recipes_average_convenience_rating'), table_name='recipes', schema='recipes_catalog')
    # ### end Alembic commands ###
