"""create index on most created_at columns

Revision ID: 635004bc0898
Revises: ba0a43b2c8d7
Create Date: 2024-11-08 17:13:39.774593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635004bc0898'
down_revision = 'ba0a43b2c8d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_iam_users_created_at'), 'users', ['created_at'], unique=False, schema='iam')
    op.create_index(op.f('ix_products_catalog_brands_created_at'), 'brands', ['created_at'], unique=False, schema='products_catalog')
    op.create_index(op.f('ix_products_catalog_products_created_at'), 'products', ['created_at'], unique=False, schema='products_catalog')
    op.create_index(op.f('ix_products_catalog_tags_created_at'), 'tags', ['created_at'], unique=False, schema='products_catalog')
    op.create_index(op.f('ix_recipes_catalog_ingredients_created_at'), 'ingredients', ['created_at'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_meals_created_at'), 'meals', ['created_at'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_ratings_created_at'), 'ratings', ['created_at'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_tags_created_at'), 'tags', ['created_at'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_shared_kernel_diet_types_created_at'), 'diet_types', ['created_at'], unique=False, schema='shared_kernel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_kernel_diet_types_created_at'), table_name='diet_types', schema='shared_kernel')
    op.drop_index(op.f('ix_recipes_catalog_tags_created_at'), table_name='tags', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_ratings_created_at'), table_name='ratings', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_meals_created_at'), table_name='meals', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_ingredients_created_at'), table_name='ingredients', schema='recipes_catalog')
    op.drop_index(op.f('ix_products_catalog_tags_created_at'), table_name='tags', schema='products_catalog')
    op.drop_index(op.f('ix_products_catalog_products_created_at'), table_name='products', schema='products_catalog')
    op.drop_index(op.f('ix_products_catalog_brands_created_at'), table_name='brands', schema='products_catalog')
    op.drop_index(op.f('ix_iam_users_created_at'), table_name='users', schema='iam')
    # ### end Alembic commands ###
