"""make menu_meals hour column nullable

Revision ID: 873041eb5161
Revises: b4cf464e03ac
Create Date: 2025-02-24 21:38:38.349664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '873041eb5161'
down_revision = 'b4cf464e03ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu_meals', 'hour',
               existing_type=postgresql.TIME(),
               nullable=True,
               schema='recipes_catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu_meals', 'hour',
               existing_type=postgresql.TIME(),
               nullable=False,
               schema='recipes_catalog')
    # ### end Alembic commands ###
