"""make some columns nullable

Revision ID: 915b9d66978e
Revises: a06d6626531a
Create Date: 2025-04-18 11:14:57.192238

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '915b9d66978e'
down_revision = 'a06d6626531a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'birthday',
               existing_type=sa.DATE(),
               nullable=True,
               schema='recipes_catalog')
    op.alter_column('clients', 'main_phone',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='recipes_catalog')
    op.alter_column('clients', 'main_email',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='recipes_catalog')
    op.alter_column('clients', 'all_phones',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               schema='recipes_catalog')
    op.alter_column('clients', 'all_emails',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               schema='recipes_catalog')
    op.alter_column('clients', 'street',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='recipes_catalog')
    op.alter_column('clients', 'number',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='recipes_catalog')
    op.alter_column('clients', 'zip_code',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='recipes_catalog')
    op.alter_column('clients', 'district',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='recipes_catalog')
    op.alter_column('clients', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='recipes_catalog')
    op.alter_column('clients', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='recipes_catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='recipes_catalog')
    op.alter_column('clients', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='recipes_catalog')
    op.alter_column('clients', 'district',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='recipes_catalog')
    op.alter_column('clients', 'zip_code',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='recipes_catalog')
    op.alter_column('clients', 'number',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='recipes_catalog')
    op.alter_column('clients', 'street',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='recipes_catalog')
    op.alter_column('clients', 'all_emails',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               schema='recipes_catalog')
    op.alter_column('clients', 'all_phones',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               schema='recipes_catalog')
    op.alter_column('clients', 'main_email',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='recipes_catalog')
    op.alter_column('clients', 'main_phone',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='recipes_catalog')
    op.alter_column('clients', 'birthday',
               existing_type=sa.DATE(),
               nullable=False,
               schema='recipes_catalog')
    # ### end Alembic commands ###
