"""make client_id on menus a foreignkey

Revision ID: a06d6626531a
Revises: a760ad3a93de
Create Date: 2025-04-14 14:02:20.446446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a06d6626531a'
down_revision = 'a760ad3a93de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_menus_client_id_clients'), 'menus', 'clients', ['client_id'], ['id'], source_schema='recipes_catalog', referent_schema='recipes_catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_menus_client_id_clients'), 'menus', schema='recipes_catalog', type_='foreignkey')
    # ### end Alembic commands ###
