"""add clients table

Revision ID: a760ad3a93de
Revises: 873041eb5161
Create Date: 2025-04-14 13:56:44.718700

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a760ad3a93de'
down_revision = '873041eb5161'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('sex', sa.String(), nullable=False),
    sa.Column('main_phone', sa.String(), nullable=False),
    sa.Column('main_email', sa.String(), nullable=False),
    sa.Column('all_phones', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('all_emails', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('zip_code', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('complement', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('discarded', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients')),
    schema='recipes_catalog'
    )
    op.create_index(op.f('ix_recipes_catalog_clients_created_at'), 'clients', ['created_at'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_clients_name'), 'clients', ['name'], unique=False, schema='recipes_catalog')
    op.create_table('clients_tags_association',
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['recipes_catalog.clients.id'], name=op.f('fk_clients_tags_association_client_id_clients')),
    sa.ForeignKeyConstraint(['tag_id'], ['shared_kernel.tags.id'], name=op.f('fk_clients_tags_association_tag_id_tags')),
    sa.PrimaryKeyConstraint('client_id', 'tag_id', name=op.f('pk_clients_tags_association')),
    schema='recipes_catalog'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients_tags_association', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_clients_name'), table_name='clients', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_clients_created_at'), table_name='clients', schema='recipes_catalog')
    op.drop_table('clients', schema='recipes_catalog')
    # ### end Alembic commands ###
