"""add liters_per_kg to products

Revision ID: bc5c8a8b3b56
Revises: cf8094919d0a
Create Date: 2025-05-08 16:46:16.789973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc5c8a8b3b56'
down_revision = 'cf8094919d0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('liters_per_kg', sa.Float(), nullable=True), schema='products_catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'liters_per_kg', schema='products_catalog')
    # ### end Alembic commands ###
