"""add shopping list columns to products

Revision ID: cf8094919d0a
Revises: d9a08a44aa8e
Create Date: 2025-05-08 16:31:05.094788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf8094919d0a'
down_revision = 'd9a08a44aa8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('kg_per_unit', sa.Float(), nullable=True), schema='products_catalog')
    op.add_column('products', sa.Column('nutrition_group', sa.String(), nullable=True), schema='products_catalog')
    op.add_column('products', sa.Column('cooking_factor', sa.Float(), nullable=True), schema='products_catalog')
    op.add_column('products', sa.Column('conservation_days', sa.Integer(), nullable=True), schema='products_catalog')
    op.add_column('products', sa.Column('substitutes', sa.String(), nullable=True), schema='products_catalog')
    op.drop_column('products', 'storable', schema='products_catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('storable', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='products_catalog')
    op.drop_column('products', 'substitutes', schema='products_catalog')
    op.drop_column('products', 'conservation_days', schema='products_catalog')
    op.drop_column('products', 'cooking_factor', schema='products_catalog')
    op.drop_column('products', 'nutrition_group', schema='products_catalog')
    op.drop_column('products', 'kg_per_unit', schema='products_catalog')
    # ### end Alembic commands ###
