"""remove columns from recipes_catalog.recipes table

Revision ID: d8bbd0841f64
Revises: 2e1e7b469cec
Create Date: 2024-04-24 15:00:44.725451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8bbd0841f64'
down_revision = '2e1e7b469cec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'is_reheatable', schema='recipes_catalog')
    op.drop_column('recipes', 'can_prepare_in_advance', schema='recipes_catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('can_prepare_in_advance', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='recipes_catalog')
    op.add_column('recipes', sa.Column('is_reheatable', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='recipes_catalog')
    # ### end Alembic commands ###
