"""add recipe sort index

Revision ID: e348e270cf80
Revises: 2a2dd2771cd1
Create Date: 2024-11-06 19:51:36.150450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e348e270cf80'
down_revision = '2a2dd2771cd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_recipes_catalog_recipes_created_at'), 'recipes', ['created_at'], unique=False, schema='recipes_catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipes_catalog_recipes_created_at'), table_name='recipes', schema='recipes_catalog')
    # ### end Alembic commands ###
