"""add utensils column to recipes_catalog.recipes

Revision ID: ec3c91988dbe
Revises: 250f49357130
Create Date: 2024-03-25 14:25:32.823314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec3c91988dbe'
down_revision = '250f49357130'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('utensils', sa.String(), nullable=True), schema='recipes_catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'utensils', schema='recipes_catalog')
    # ### end Alembic commands ###
