"""add multiple columns to meals

Revision ID: ed504305f201
Revises: e348e270cf80
Create Date: 2024-11-08 14:29:27.873113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed504305f201'
down_revision = 'e348e270cf80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meals_allergens_association',
    sa.Column('meal_id', sa.String(), nullable=False),
    sa.Column('allergen_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['allergen_name'], ['shared_kernel.allergens.id'], name=op.f('fk_meals_allergens_association_allergen_name_allergens')),
    sa.ForeignKeyConstraint(['meal_id'], ['recipes_catalog.meals.id'], name=op.f('fk_meals_allergens_association_meal_id_meals')),
    sa.PrimaryKeyConstraint('meal_id', 'allergen_name', name=op.f('pk_meals_allergens_association')),
    schema='recipes_catalog'
    )
    op.create_table('meals_cuisines_association',
    sa.Column('meal_id', sa.String(), nullable=False),
    sa.Column('cuisine_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cuisine_id'], ['shared_kernel.cuisines.id'], name=op.f('fk_meals_cuisines_association_cuisine_id_cuisines')),
    sa.ForeignKeyConstraint(['meal_id'], ['recipes_catalog.meals.id'], name=op.f('fk_meals_cuisines_association_meal_id_meals')),
    sa.PrimaryKeyConstraint('meal_id', 'cuisine_id', name=op.f('pk_meals_cuisines_association')),
    schema='recipes_catalog'
    )
    op.create_table('meals_diet_types_association',
    sa.Column('meal_id', sa.String(), nullable=False),
    sa.Column('diet_type_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['diet_type_id'], ['shared_kernel.diet_types.id'], name=op.f('fk_meals_diet_types_association_diet_type_id_diet_types')),
    sa.ForeignKeyConstraint(['meal_id'], ['recipes_catalog.meals.id'], name=op.f('fk_meals_diet_types_association_meal_id_meals')),
    sa.PrimaryKeyConstraint('meal_id', 'diet_type_id', name=op.f('pk_meals_diet_types_association')),
    schema='recipes_catalog'
    )
    op.create_table('meals_flavors_association',
    sa.Column('meal_id', sa.String(), nullable=False),
    sa.Column('flavor_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['flavor_id'], ['shared_kernel.flavors.id'], name=op.f('fk_meals_flavors_association_flavor_id_flavors')),
    sa.ForeignKeyConstraint(['meal_id'], ['recipes_catalog.meals.id'], name=op.f('fk_meals_flavors_association_meal_id_meals')),
    sa.PrimaryKeyConstraint('meal_id', 'flavor_id', name=op.f('pk_meals_flavors_association')),
    schema='recipes_catalog'
    )
    op.create_table('meals_tags_association',
    sa.Column('meal_id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['recipes_catalog.meals.id'], name=op.f('fk_meals_tags_association_meal_id_meals')),
    sa.ForeignKeyConstraint(['tag_id'], ['recipes_catalog.tags.id'], name=op.f('fk_meals_tags_association_tag_id_tags')),
    sa.PrimaryKeyConstraint('meal_id', 'tag_id', name=op.f('pk_meals_tags_association')),
    schema='recipes_catalog'
    )
    op.create_table('meals_textures_association',
    sa.Column('meal_id', sa.String(), nullable=False),
    sa.Column('texture_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['recipes_catalog.meals.id'], name=op.f('fk_meals_textures_association_meal_id_meals')),
    sa.ForeignKeyConstraint(['texture_id'], ['shared_kernel.textures.id'], name=op.f('fk_meals_textures_association_texture_id_textures')),
    sa.PrimaryKeyConstraint('meal_id', 'texture_id', name=op.f('pk_meals_textures_association')),
    schema='recipes_catalog'
    )
    op.add_column('meals', sa.Column('total_time', sa.Integer(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('like', sa.Boolean(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('weight_in_grams', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('calorie_density', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('carbo_percentage', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('protein_percentage', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('total_fat_percentage', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('calories', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('protein', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('carbohydrate', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('total_fat', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('saturated_fat', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('trans_fat', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('dietary_fiber', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('sodium', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('arachidonic_acid', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('ashes', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('dha', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('epa', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('sugar', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('starch', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('biotin', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('boro', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('caffeine', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('calcium', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('chlorine', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('copper', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('cholesterol', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('choline', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('chrome', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('dextrose', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('sulfur', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('phenylalanine', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('iron', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('insoluble_fiber', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('soluble_fiber', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('fluor', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('phosphorus', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('fructo_oligosaccharides', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('fructose', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('galacto_oligosaccharides', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('galactose', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('glucose', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('glucoronolactone', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('monounsaturated_fat', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('polyunsaturated_fat', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('guarana', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('inositol', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('inulin', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('iodine', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('l_carnitine', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('l_methionine', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('lactose', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('magnesium', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('maltose', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('manganese', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('molybdenum', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('linolenic_acid', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('linoleic_acid', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('omega_7', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('omega_9', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('oleic_acid', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('other_carbo', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('polydextrose', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('polyols', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('potassium', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('sacarose', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('selenium', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('silicon', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('sorbitol', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('sucralose', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('taurine', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('vitamin_a', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('vitamin_b1', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('vitamin_b2', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('vitamin_b3', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('vitamin_b5', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('vitamin_b6', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('folic_acid', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('vitamin_b12', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('vitamin_c', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('vitamin_d', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('vitamin_e', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('vitamin_k', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('zinc', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('retinol', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('thiamine', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('riboflavin', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('pyridoxine', sa.Float(), nullable=True), schema='recipes_catalog')
    op.add_column('meals', sa.Column('niacin', sa.Float(), nullable=True), schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_meals_author_id'), 'meals', ['author_id'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_meals_calorie_density'), 'meals', ['calorie_density'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_meals_calories'), 'meals', ['calories'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_meals_carbo_percentage'), 'meals', ['carbo_percentage'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_meals_carbohydrate'), 'meals', ['carbohydrate'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_meals_like'), 'meals', ['like'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_meals_protein'), 'meals', ['protein'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_meals_protein_percentage'), 'meals', ['protein_percentage'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_meals_saturated_fat'), 'meals', ['saturated_fat'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_meals_sugar'), 'meals', ['sugar'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_meals_total_fat'), 'meals', ['total_fat'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_meals_total_fat_percentage'), 'meals', ['total_fat_percentage'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_meals_total_time'), 'meals', ['total_time'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_meals_trans_fat'), 'meals', ['trans_fat'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_meals_weight_in_grams'), 'meals', ['weight_in_grams'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_ratings_convenience'), 'ratings', ['convenience'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_ratings_taste'), 'ratings', ['taste'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_recipes_author_id'), 'recipes', ['author_id'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_recipes_saturated_fat'), 'recipes', ['saturated_fat'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_recipes_sugar'), 'recipes', ['sugar'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_recipes_trans_fat'), 'recipes', ['trans_fat'], unique=False, schema='recipes_catalog')
    op.create_index(op.f('ix_recipes_catalog_recipes_weight_in_grams'), 'recipes', ['weight_in_grams'], unique=False, schema='recipes_catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipes_catalog_recipes_weight_in_grams'), table_name='recipes', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_recipes_trans_fat'), table_name='recipes', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_recipes_sugar'), table_name='recipes', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_recipes_saturated_fat'), table_name='recipes', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_recipes_author_id'), table_name='recipes', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_ratings_taste'), table_name='ratings', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_ratings_convenience'), table_name='ratings', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_meals_weight_in_grams'), table_name='meals', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_meals_trans_fat'), table_name='meals', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_meals_total_time'), table_name='meals', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_meals_total_fat_percentage'), table_name='meals', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_meals_total_fat'), table_name='meals', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_meals_sugar'), table_name='meals', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_meals_saturated_fat'), table_name='meals', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_meals_protein_percentage'), table_name='meals', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_meals_protein'), table_name='meals', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_meals_like'), table_name='meals', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_meals_carbohydrate'), table_name='meals', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_meals_carbo_percentage'), table_name='meals', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_meals_calories'), table_name='meals', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_meals_calorie_density'), table_name='meals', schema='recipes_catalog')
    op.drop_index(op.f('ix_recipes_catalog_meals_author_id'), table_name='meals', schema='recipes_catalog')
    op.drop_column('meals', 'niacin', schema='recipes_catalog')
    op.drop_column('meals', 'pyridoxine', schema='recipes_catalog')
    op.drop_column('meals', 'riboflavin', schema='recipes_catalog')
    op.drop_column('meals', 'thiamine', schema='recipes_catalog')
    op.drop_column('meals', 'retinol', schema='recipes_catalog')
    op.drop_column('meals', 'zinc', schema='recipes_catalog')
    op.drop_column('meals', 'vitamin_k', schema='recipes_catalog')
    op.drop_column('meals', 'vitamin_e', schema='recipes_catalog')
    op.drop_column('meals', 'vitamin_d', schema='recipes_catalog')
    op.drop_column('meals', 'vitamin_c', schema='recipes_catalog')
    op.drop_column('meals', 'vitamin_b12', schema='recipes_catalog')
    op.drop_column('meals', 'folic_acid', schema='recipes_catalog')
    op.drop_column('meals', 'vitamin_b6', schema='recipes_catalog')
    op.drop_column('meals', 'vitamin_b5', schema='recipes_catalog')
    op.drop_column('meals', 'vitamin_b3', schema='recipes_catalog')
    op.drop_column('meals', 'vitamin_b2', schema='recipes_catalog')
    op.drop_column('meals', 'vitamin_b1', schema='recipes_catalog')
    op.drop_column('meals', 'vitamin_a', schema='recipes_catalog')
    op.drop_column('meals', 'taurine', schema='recipes_catalog')
    op.drop_column('meals', 'sucralose', schema='recipes_catalog')
    op.drop_column('meals', 'sorbitol', schema='recipes_catalog')
    op.drop_column('meals', 'silicon', schema='recipes_catalog')
    op.drop_column('meals', 'selenium', schema='recipes_catalog')
    op.drop_column('meals', 'sacarose', schema='recipes_catalog')
    op.drop_column('meals', 'potassium', schema='recipes_catalog')
    op.drop_column('meals', 'polyols', schema='recipes_catalog')
    op.drop_column('meals', 'polydextrose', schema='recipes_catalog')
    op.drop_column('meals', 'other_carbo', schema='recipes_catalog')
    op.drop_column('meals', 'oleic_acid', schema='recipes_catalog')
    op.drop_column('meals', 'omega_9', schema='recipes_catalog')
    op.drop_column('meals', 'omega_7', schema='recipes_catalog')
    op.drop_column('meals', 'linoleic_acid', schema='recipes_catalog')
    op.drop_column('meals', 'linolenic_acid', schema='recipes_catalog')
    op.drop_column('meals', 'molybdenum', schema='recipes_catalog')
    op.drop_column('meals', 'manganese', schema='recipes_catalog')
    op.drop_column('meals', 'maltose', schema='recipes_catalog')
    op.drop_column('meals', 'magnesium', schema='recipes_catalog')
    op.drop_column('meals', 'lactose', schema='recipes_catalog')
    op.drop_column('meals', 'l_methionine', schema='recipes_catalog')
    op.drop_column('meals', 'l_carnitine', schema='recipes_catalog')
    op.drop_column('meals', 'iodine', schema='recipes_catalog')
    op.drop_column('meals', 'inulin', schema='recipes_catalog')
    op.drop_column('meals', 'inositol', schema='recipes_catalog')
    op.drop_column('meals', 'guarana', schema='recipes_catalog')
    op.drop_column('meals', 'polyunsaturated_fat', schema='recipes_catalog')
    op.drop_column('meals', 'monounsaturated_fat', schema='recipes_catalog')
    op.drop_column('meals', 'glucoronolactone', schema='recipes_catalog')
    op.drop_column('meals', 'glucose', schema='recipes_catalog')
    op.drop_column('meals', 'galactose', schema='recipes_catalog')
    op.drop_column('meals', 'galacto_oligosaccharides', schema='recipes_catalog')
    op.drop_column('meals', 'fructose', schema='recipes_catalog')
    op.drop_column('meals', 'fructo_oligosaccharides', schema='recipes_catalog')
    op.drop_column('meals', 'phosphorus', schema='recipes_catalog')
    op.drop_column('meals', 'fluor', schema='recipes_catalog')
    op.drop_column('meals', 'soluble_fiber', schema='recipes_catalog')
    op.drop_column('meals', 'insoluble_fiber', schema='recipes_catalog')
    op.drop_column('meals', 'iron', schema='recipes_catalog')
    op.drop_column('meals', 'phenylalanine', schema='recipes_catalog')
    op.drop_column('meals', 'sulfur', schema='recipes_catalog')
    op.drop_column('meals', 'dextrose', schema='recipes_catalog')
    op.drop_column('meals', 'chrome', schema='recipes_catalog')
    op.drop_column('meals', 'choline', schema='recipes_catalog')
    op.drop_column('meals', 'cholesterol', schema='recipes_catalog')
    op.drop_column('meals', 'copper', schema='recipes_catalog')
    op.drop_column('meals', 'chlorine', schema='recipes_catalog')
    op.drop_column('meals', 'calcium', schema='recipes_catalog')
    op.drop_column('meals', 'caffeine', schema='recipes_catalog')
    op.drop_column('meals', 'boro', schema='recipes_catalog')
    op.drop_column('meals', 'biotin', schema='recipes_catalog')
    op.drop_column('meals', 'starch', schema='recipes_catalog')
    op.drop_column('meals', 'sugar', schema='recipes_catalog')
    op.drop_column('meals', 'epa', schema='recipes_catalog')
    op.drop_column('meals', 'dha', schema='recipes_catalog')
    op.drop_column('meals', 'ashes', schema='recipes_catalog')
    op.drop_column('meals', 'arachidonic_acid', schema='recipes_catalog')
    op.drop_column('meals', 'sodium', schema='recipes_catalog')
    op.drop_column('meals', 'dietary_fiber', schema='recipes_catalog')
    op.drop_column('meals', 'trans_fat', schema='recipes_catalog')
    op.drop_column('meals', 'saturated_fat', schema='recipes_catalog')
    op.drop_column('meals', 'total_fat', schema='recipes_catalog')
    op.drop_column('meals', 'carbohydrate', schema='recipes_catalog')
    op.drop_column('meals', 'protein', schema='recipes_catalog')
    op.drop_column('meals', 'calories', schema='recipes_catalog')
    op.drop_column('meals', 'total_fat_percentage', schema='recipes_catalog')
    op.drop_column('meals', 'protein_percentage', schema='recipes_catalog')
    op.drop_column('meals', 'carbo_percentage', schema='recipes_catalog')
    op.drop_column('meals', 'calorie_density', schema='recipes_catalog')
    op.drop_column('meals', 'weight_in_grams', schema='recipes_catalog')
    op.drop_column('meals', 'like', schema='recipes_catalog')
    op.drop_column('meals', 'total_time', schema='recipes_catalog')
    op.drop_table('meals_textures_association', schema='recipes_catalog')
    op.drop_table('meals_tags_association', schema='recipes_catalog')
    op.drop_table('meals_flavors_association', schema='recipes_catalog')
    op.drop_table('meals_diet_types_association', schema='recipes_catalog')
    op.drop_table('meals_cuisines_association', schema='recipes_catalog')
    op.drop_table('meals_allergens_association', schema='recipes_catalog')
    # ### end Alembic commands ###
